/*
  Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  Permission is hereby granted, free of charge, to any person obtaining a copy of this
  software and associated documentation files (the "Software"), to deal in the Software
  without restriction, including without limitation the rights to use, copy, modify,
  merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
  permit persons to whom the Software is furnished to do so.
  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
  INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
  PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
  OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
  SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

#include <pgmspace.h>

#define SECRET
#define THINGNAME "tCrack"

const char AWS_IOT_ENDPOINT[] = "a345vu73g6bbpf-ats.iot.us-east-1.amazonaws.com";

// Amazon Root CA 1
static const char AWS_CERT_CA[] PROGMEM = R"EOF(
-----BEGIN CERTIFICATE-----
MIIDQTCCAimgAwIBAgITBmyfz5m/jAo54vB4ikPmljZbyjANBgkqhkiG9w0BAQsF
ADA5MQswCQYDVQQGEwJVUzEPMA0GA1UEChMGQW1hem9uMRkwFwYDVQQDExBBbWF6
b24gUm9vdCBDQSAxMB4XDTE1MDUyNjAwMDAwMFoXDTM4MDExNzAwMDAwMFowOTEL
MAkGA1UEBhMCVVMxDzANBgNVBAoTBkFtYXpvbjEZMBcGA1UEAxMQQW1hem9uIFJv
b3QgQ0EgMTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALJ4gHHKeNXj
ca9HgFB0fW7Y14h29Jlo91ghYPl0hAEvrAIthtOgQ3pOsqTQNroBvo3bSMgHFzZM
9O6II8c+6zf1tRn4SWiw3te5djgdYZ6k/oI2peVKVuRF4fn9tBb6dNqcmzU5L/qw
IFAGbHrQgLKm+a/sRxmPUDgH3KKHOVj4utWp+UhnMJbulHheb4mjUcAwhmahRWa6
VOujw5H5SNz/0egwLX0tdHA114gk957EWW67c4cX8jJGKLhD+rcdqsq08p8kDi1L
93FcXmn/6pUCyziKrlA4b9v7LWIbxcceVOF34GfID5yHI9Y/QCB/IIDEgEw+OyQm
jgSubJrIqg0CAwEAAaNCMEAwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMC
AYYwHQYDVR0OBBYEFIQYzIU07LwMlJQuCFmcx7IQTgoIMA0GCSqGSIb3DQEBCwUA
A4IBAQCY8jdaQZChGsV2USggNiMOruYou6r4lK5IpDB/G/wkjUu0yKGX9rbxenDI
U5PMCCjjmCXPI6T53iHTfIUJrU6adTrCC2qJeHZERxhlbI1Bjjt/msv0tadQ1wUs
N+gDS63pYaACbvXy8MWy7Vu33PqUXHeeE6V/Uq2V8viTO96LXFvKWlJbYK8U90vv
o/ufQJVtMVT8QtPHRh8jrdkPSHCa2XV4cdFyQzR1bldZwgJcJmApzyMZFo6IQ6XU
5MsI+yMRQ+hDKXJioaldXgjUkK642M4UwtBV8ob2xJNDd2ZhwLnoQdeXeGADbkpy
rqXRfboQnoZsG4q5WTP468SQvvG5
-----END CERTIFICATE-----
)EOF";

// Device Certificate
static const char AWS_CERT_CRT[] PROGMEM = R"KEY(
-----BEGIN CERTIFICATE-----
MIIDWTCCAkGgAwIBAgIUVCjDF2fDT3qYbz6fJbIbthv3GFswDQYJKoZIhvcNAQEL
BQAwTTFLMEkGA1UECwxCQW1hem9uIFdlYiBTZXJ2aWNlcyBPPUFtYXpvbi5jb20g
SW5jLiBMPVNlYXR0bGUgU1Q9V2FzaGluZ3RvbiBDPVVTMB4XDTI0MDcxNDAxMDE1
MloXDTQ5MTIzMTIzNTk1OVowHjEcMBoGA1UEAwwTQVdTIElvVCBDZXJ0aWZpY2F0
ZTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALLSbyHh065nisUqyFRD
g0m7aj6VpQ64+Z9HQSmk3hMD9452V+wUTPvxWaZo0ysbeoDFJXOlWOQZ5kP/cB9+
/pVQUx3fqRWanweR5VEoK4OGcv5Bj54gcZV9n6KATiMVlU2jR/DDzVUWu7dMZ3QG
jIOhqUij2NpZKw1Y+T7cfTp4p4QOyn5sY6W5CHyC44pFg8e2rUs7kUvgGU/JWs1N
KsqwUrNYYwjl+Cvh9HVxjTBYFuv13PFdKpfCEHEpFlPnNkC9EGgXzSCTVJ5SLezQ
l39fVo8dVExsuo9D1YNPV7aWYxkT26sugKvdKQdJHqhZQYjNjUm05aCAXHkbNQ1A
QnMCAwEAAaNgMF4wHwYDVR0jBBgwFoAUI98JNRKK4qbRjblfkFDmEQat9hcwHQYD
VR0OBBYEFODr+gzyEGeOEOLj6uwCz695GGMFMAwGA1UdEwEB/wQCMAAwDgYDVR0P
AQH/BAQDAgeAMA0GCSqGSIb3DQEBCwUAA4IBAQAGT2HMUBnkO0yntRLFwaZoRdQw
UHPLFwGHir8j8aWNSXr9+Rp02P5ot6FQE7sbf1SPjg7LCxoS+lJHlmjssrlBzzXV
CXLbMOGD3LBAQoNoEQm4G2AcOthxtMrjFFVx/nwdP+3AqWK4+vRTIDuemOtukgbk
IUhbPxH6b7hnhCVUnqX42xXOKPFrtZp+yA/Qd2h4lhUh2iAr2A4Lj8kq1tWuC8xD
KcFcEzAMUZjeMb4+Al9uSPLi6qeYzvDld4HnsMiYi08SfE1osKaJNMXL/S6a0Toy
BYOV4tlL1tmbqmZ631plqOi1UA2M61RbjFo7bvvjGlFTkKxTy/hdXCzxXH1X
-----END CERTIFICATE-----
)KEY";

// Device Private Key
static const char AWS_CERT_PRIVATE[] PROGMEM = R"KEY(
-----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEAstJvIeHTrmeKxSrIVEODSbtqPpWlDrj5n0dBKaTeEwP3jnZX
7BRM+/FZpmjTKxt6gMUlc6VY5BnmQ/9wH37+lVBTHd+pFZqfB5HlUSgrg4Zy/kGP
niBxlX2fooBOIxWVTaNH8MPNVRa7t0xndAaMg6GpSKPY2lkrDVj5Ptx9OninhA7K
fmxjpbkIfILjikWDx7atSzuRS+AZT8lazU0qyrBSs1hjCOX4K+H0dXGNMFgW6/Xc
8V0ql8IQcSkWU+c2QL0QaBfNIJNUnlIt7NCXf19Wjx1UTGy6j0PVg09XtpZjGRPb
qy6Aq90pB0keqFlBiM2NSbTloIBceRs1DUBCcwIDAQABAoIBAConUw1Ap97QB7Vs
3WaHt7Y02NnB+vPahPWYHXNMqxD+eWf628UKEA/AGCsTQNxDkQAz+R0m2CqFNHPJ
DkxOaoMWOVGsfLZcCasGKHGWL5PEqOzo1YsoCL59q5jp+AFrQBPaLsZB0fCB+GRA
PY7rUEpjXH2EKkVmibCOzcqUvWx/yb6kMl9agfGZhJTBPichF4LbxMlpZNSuhDvL
Gwhaqz8c2QYIRQmNBA6mZJovXjrgdjBGbo+3mMh4L4cosjV0JK5dm6AYVALKGsZ6
vf5mjHMKTaUYuc+1IY6ucpbhJEZmDG4VDFow9KSxtkF9Gn2eg+GdCFY+DkxpklRm
9F26B/ECgYEA3yooy0dvctfn26sAX8i/UL7IOOQ6hKtVnEBKW3kuNeDq4X28Qmzg
Ka12/OtWX+OaoA9ojJC9rfbLPk79QpaQw3ZdmGrm1lIP6UKnb/hgYCI0LH/zn9yR
x3RP8YxvsT7LMfT9va3MXDbQTvLAIul3uJ7+GV5M3wgOr5keKfGk29kCgYEAzSIK
K6GwPyow2dx3SAM5CSljhAJI4QuIK4cdLwcjfLJbgPhX42aD4fQLob5e2DjTyKzZ
9LkCG2hb/BWsV84ibk7ZuiTct5Zz8xhdbpy4jLWo9RODzQ3CCiABtLdL513BgD9B
HFykl+1lnybSuR6gSbG0HK/lBpqzJnRKg9jN3SsCgYEAwgiQC58C4eGjsLVPz/hl
j7kxsXWPA8dM2lxzynDkouf6kTCXvVGY3eP67xFXumvVB5IeHwnCQj2wnW5keb8c
AzcpTdq09mfHedMAbjSQ50UWBBMEKlzHS5pv399xRbUJS1huPrucUhk+qUYblL9V
3uoumLQLNmh1DGyfc2ytIJECgYBIfdcKREF8kPRiiT69/CWTz0STyhrnLKQafc0a
aXNpBb7AfQLSIdBJcW0K47OwxaRSLoN3sEnGVcLr+tzEytvwD31yAsTdPBYNunaK
OGgfkbL7qMHTHSGNYnI34u63/LH9GF1yIGsqJYLcE2Q0d1Y9tMbpvF87TkAxPrd2
kI9vsQKBgQDCYbLHinAM8gTebXWMNWtPA4/AHhxKcT8dD9zkZM9ClF6ADG5s+oGp
6qVVXcb2+tStV88XHcp78dTyG3ZtntTo/K75pYOCmcmq2n+ZrmcovltacsS4aOlh
YFxNMIm4pCGPEosA8Xc+X8XysISK+6mV/j8SRmHI38CDlWvea4HyiQ==
-----END RSA PRIVATE KEY-----
)KEY";
