name: Deploy Doxygen Documentation

on:
  push:
    branches:
      - master  
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    - name: Generate Doxygen Documentation
      run: doxygen docs/Doxyfile
      working-directory: ${{ github.workspace }} 

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: temp_docs/html  
        CLEAN: true
