name: Deploy Doxygen Documentation

on:
  push:
    branches:
      - master  
  workflow_dispatch:

jobs:
  deploy-docs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen

    - name: Generate Doxygen Documentation
      run: doxygen docs/Doxyfile
      working-directory: ${{ github.workspace }} # Ensure you are in the root directory of your repo

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages   # Ensures that the output is pushed to the gh-pages branch
        FOLDER: docs/html  # Update this if your HTML output directory is different
        CLEAN: true        # Optionally clean out old files in the gh-pages branch
